openapi: 3.0.0
info:
  title: API Sistema Acadêmico
  description: Esta documentação guia a gestão de pessoas, cursos, categorias e matriculas na API
  version: 1.0.0
  contact:
    name: Guilherme Gomes
    email: guiigomes0734@gmail.com
  
servers:
  - url: http://localhost:3000/
    description: Servidor de Desenvolvimento Local

tags:
  - name: Pessoas
    description: Cadastro e gerenciamento de pessoas (alunos e docentes)
  - name: Categorias
    description: Cadastro e gerenciamento de categorias
  - name: Cursos
    description: Cadastro e gerenciamento de cursos
  - name: Matriculas
    description: Cadastro e gerenciamento de matriculas

paths:
  /pessoas:
    get:
      tags:
        - Pessoas
      summary: Busca os usuários ativos
      description: Retorna todos os usuários cadastrados (apenas usuários ativos no sistema)
      parameters:
        - name: nome
          required: false
          in: query
          description: Nome do usuário
          schema:
            type: string
        - name: email
          required: false
          in: query
          description: Email cadastrado do usuário
          schema:
            type: string
        - name: cpf
          required: false
          in: query
          description: CPF do usuário
          schema:
            type: string
        - name: role
          required: false
          in: query
          description: Função do usuário (estudante ou docente)
          schema:
            type: string
        - name: pagina
          required: false
          in: query
          description: Selecionar página/Filtrar por página
          schema:
            type: integer
        - name: limite
          required: false
          in: query
          description: Definir um limite de dados retornados por página
          schema:
            type: integer
        - name: ordem
          required: false
          in: query
          description: Definir ordem de retorno dos dados
          schema:
            type: string
            example: "id:asc"

      responses:
        "200":
          description: Lista de usuários retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PessoaResponse"
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
    post:
      tags:
        - Pessoas
      summary: Cadastra um novo usuário
      description: Cria um novo usuário a partir das informações enviadas na requisição
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PessoaRequest"
      responses:
        "201":
          description: Usuário cadastrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PessoaResponse"
        "400":
          description: Erro de validação
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: "Um ou mais valores fornecidos não são válidos"
                status: 400

        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
  /pessoas/todos:
    get:
      tags:
        - Pessoas
      summary: Busca todos os usuários
      description: Retorna todos os usuários cadastrados, sejam eles ativos ou inativos
      parameters:
        - name: nome
          required: false
          in: query
          description: Nome do usuário
          schema:
            type: string
        - name: email
          required: false
          in: query
          description: Email cadastrado do usuário
          schema:
            type: string
        - name: cpf
          required: false
          in: query
          description: CPF do usuário
          schema:
            type: string
        - name: role
          required: false
          in: query
          description: Função do usuário (estudante ou docente)
          schema:
            type: string
        - name: pagina
          required: false
          in: query
          description: Selecionar página/Filtrar por página
          schema:
            type: integer
        - name: limite
          required: false
          in: query
          description: Definir um limite de dados retornados por página
          schema:
            type: integer
        - name: ordem
          required: false
          in: query
          description: Definir ordem de retorno dos dados
          schema:
            type: string
            example: "id:asc"
      responses:
        "200":
          description: Lista de usuários retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PessoaResponse"
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
  /pessoas/{id}:
    get:
      tags:
        - Pessoas
      summary: Busca um usuário pelo ID
      description: Busca um usuário pelo ID (apenas usuários ativos no sistema)
      parameters:
        - name: id
          in: path
          required: true
          description: ID numérico do usuário
          schema:
            type: integer
        
      responses:
        "200":
          description: Usuário encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PessoaResponse"
        "400":
          description: "ID com formato inválido"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                  message: "Um ou mais valores fornecidos estão incorretos"
                  status: 400
        "404":
          description: "ID inexistente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: ID fornecido não encontrado
                status: 404
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
    put:
      tags:
        - Pessoas
      summary: Atualiza um usuário pelo ID
      description: Atualiza um usuário pelo ID a partir das informações enviadas na requisição (apenas usuários ativos no sistema)
      parameters:
        - name: id
          required: true
          in: path
          description: ID numérico do usuário
          schema:
            type: integer

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PessoaRequest"
      responses:
        "200":
          description: "Registro atualizado com sucesso!"
          content:
            text/plain:
              schema:
                type: string
                example: "Registro atualizado com sucesso!"
        "400":
          description: Erro de validação ou ID com formato inválido
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              examples:
                DadosInvalidos:
                  summary: Dados inválidos
                  value:
                    message: "Um ou mais valores fornecidos não são válidos"
                    status: 400
                idInvalido:
                  summary: "ID com formato inválido"
                  value:
                    message: "Um ou mais valores fornecidos estão incorretos"
                    status: 400
        "404":
          description: "ID inexistente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: ID fornecido não encontrado
                status: 404
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
    delete:
      tags:
        - Pessoas
      summary: Deleta um usuário pelo ID
      description: Remove um usuário do sistema pelo ID (apenas usuários ativos no sistema)
      parameters:
        - name: id
          required: true
          in: path
          description: ID numérico do usuário
          schema:
            type: integer
      responses:
        "200":
          description: "Registro removido com sucesso!"
          content:
            text/plain:
              schema:
                type: string
                example: "Registro removido com sucesso!"
        "400":
          description: "ID com formato inválido"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: "Um ou mais valores fornecidos estão incorretos"
                status: 400
        "404":
          description: "ID inexistente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: ID fornecido não encontrado
                status: 404
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
  /pessoas/{estudante_id}/cancelar:
    put:
      tags:
        - Pessoas
      summary: Inativa um usuário e cancela suas matriculas
      description: Inativa o usuário no sistema e cancela todas suas respectivas matriculas ativas (apenas usuários ativos no sistema)
      parameters:
        - name: estudante_id
          required: true
          in: path
          description: ID numérico do usuário
          schema:
            type: integer
      responses:
        "200":
          description: "Estudante inativado e matrículas canceladas com sucesso!"
          content:
            text/plain:
              schema:
                type: string
                example: "Registro atualizado com sucesso!"
        "400":
          description: "ID com formato inválido"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: "Um ou mais valores fornecidos estão incorretos"
                status: 400
        "404":
          description: "ID inexistente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: ID fornecido não encontrado
                status: 404
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
  /pessoas/{estudante_id}/matriculas:
    get:
      tags:
        - Pessoas
      summary: Busca as matriculas de um usuário
      description: Busca todas as matriculas com status matriculado de um usuário pelo seu ID
      parameters:
        - name: estudante_id
          in: path
          required: true
          description: ID numérico do usuário
          schema:
            type: integer
        - name: pagina
          required: false
          in: query
          description: Selecionar página/Filtrar por página
          schema:
            type: integer
        - name: limite
          required: false
          in: query
          description: Definir um limite de dados retornados por página
          schema:
            type: integer
        - name: ordem
          required: false
          in: query
          description: Definir ordem de retorno dos dados
          schema:
            type: string
            example: "id:asc"
        
      responses:
        "200":
          description: Matriculas do usuário encontradas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MatriculaResponse"
        "400":
          description: "ID com formato inválido"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: "Um ou mais valores fornecidos estão incorretos"
                status: 400
        "404":
          description: "ID inexistente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: ID fornecido não encontrado
                status: 404
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
    post:
      tags:
        - Pessoas
      summary: Cadastra uma nova matricula de um usuário
      description: Cria uma nova matricula para um usuário pelo seu ID
      parameters:
        - name: estudante_id
          in: path
          required: true
          description: ID numérico do usuário
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MatriculaRequest"
      responses:
        "201":
          description: Matricula cadastrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatriculaResponse"
        "400":
          description: Erro de validação ou violação de chave estrangeira ou ID com formato inválido
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              examples:
                ViolacaoFK:
                  summary: Violação de chave estrangeira
                  value:
                    message: "Violação de chave estrangeira. Um ou mais valores informados não existem no sistema."
                    status: 400
                DadosInvalidos:
                  summary: Dados inválidos
                  value:
                    message: "Um ou mais valores fornecidos não são válidos"
                    status: 400
                idInvalido:
                  summary: "ID com formato inválido"
                  value:
                    message: "Um ou mais valores fornecidos estão incorretos"
                    status: 400
        "404":
          description: "ID inexistente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: ID fornecido não encontrado
                status: 404
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse" 
  /pessoas/{estudante_id}/matriculas/todas:
    get:
      tags:
        - Pessoas
      summary: Busca todas as matriculas de um usuário
      description: Busca todas as matriculas de um usuário pelo seu ID independente do status da matricula
      parameters:
        - name: estudante_id
          in: path
          required: true
          description: ID numérico do usuário
          schema:
            type: integer
        - name: pagina
          required: false
          in: query
          description: Selecionar página/Filtrar por página
          schema:
            type: integer
        - name: limite
          required: false
          in: query
          description: Definir um limite de dados retornados por página
          schema:
            type: integer
        - name: ordem
          required: false
          in: query
          description: Definir ordem de retorno dos dados
          schema:
            type: string
            example: "id:asc"
        
      responses:
        "200":
          description: Matriculas do usuário encontradas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MatriculaResponse"
        "400":
          description: "ID com formato inválido"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: "Um ou mais valores fornecidos estão incorretos"
                status: 400
        "404":
          description: "ID inexistente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: ID fornecido não encontrado
                status: 404
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
  /pessoas/{estudante_id}/matriculas/canceladas:
    get:
      tags:
        - Pessoas
      summary: Busca as matriculas canceladas de um usuário
      description: Busca todas as matriculas com status cancelado de um usuário pelo seu ID
      parameters:
        - name: estudante_id
          in: path
          required: true
          description: ID numérico do usuário
          schema:
            type: integer
        - name: pagina
          required: false
          in: query
          description: Selecionar página/Filtrar por página
          schema:
            type: integer
        - name: limite
          required: false
          in: query
          description: Definir um limite de dados retornados por página
          schema:
            type: integer
        - name: ordem
          required: false
          in: query
          description: Definir ordem de retorno dos dados
          schema:
            type: string
            example: "id:asc"
        
      responses:
        "200":
          description: Matriculas do usuário encontradas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MatriculaResponse"
        "400":
          description: "ID com formato inválido"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: "Um ou mais valores fornecidos estão incorretos"
                status: 400
        "404":
          description: "ID inexistente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: ID fornecido não encontrado
                status: 404
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
  /pessoas/{estudante_id}/matriculas/total-confirmadas:
    get:
      tags:
        - Pessoas
      summary: Busca e conta as matriculas de um usuário
      description: Busca e conta todas as matriculas com status matriculado de um usuário pelo seu ID
      parameters:
        - name: estudante_id
          in: path
          required: true
          description: ID numérico do usuário
          schema:
            type: integer
        - name: pagina
          required: false
          in: query
          description: Selecionar página/Filtrar por página
          schema:
            type: integer
        - name: limite
          required: false
          in: query
          description: Definir um limite de dados retornados por página
          schema:
            type: integer
        - name: ordem
          required: false
          in: query
          description: Definir ordem de retorno dos dados
          schema:
            type: string
            example: "id:asc"
        
      responses:
        "200":
          description: Matriculas do usuário encontradas
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 1
                  rows:
                    type: array
                    items:
                      $ref: "#/components/schemas/MatriculaResponse"

        "400":
          description: "ID com formato inválido"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: "Um ou mais valores fornecidos estão incorretos"
                status: 400
        "404":
          description: "ID inexistente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: ID fornecido não encontrado
                status: 404
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
  /pessoas/{estudante_id}/matriculas/{id}:
    get:
      tags:
        - Pessoas
      summary: Busca uma matricula de um usuário
      description: Busca uma matricula pelo seu ID de um usuário pelo seu ID
      parameters:
        - name: estudante_id
          in: path
          required: true
          description: ID numérico do usuário
          schema:
            type: integer
        - name: id
          in: path
          required: true
          description: ID numérico da matrícula
          schema:
            type: integer
        
      responses:
        "200":
          description: Matricula do usuário encontrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatriculaResponse"
        "400":
          description: "ID com formato inválido"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: "Um ou mais valores fornecidos estão incorretos"
                status: 400
        "404":
          description: "ID inexistente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: ID fornecido não encontrado
                status: 404
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
    put:
      tags:
        - Pessoas
      summary: Atualiza uma matricula de um usuário
      description: Atualiza uma matricula pelo seu ID de um usuário pelo seu ID
      parameters:
        - name: estudante_id
          in: path
          required: true
          description: ID numérico do usuário
          schema:
            type: integer
        - name: id
          in: path
          required: true
          description: ID numérico da matricula
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MatriculaRequest"
      responses:
        "200":
          description: Matricula atualizada com sucesso!
          content:
            text/plain:
              schema:
                type: string
                example: "Registro atualizado com sucesso!"
        "400":
          description: Erro de validação ou violação de chave estrangeira ou ID com formato inválido
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              examples:
                ViolacaoFK:
                  summary: Violação de chave estrangeira
                  value:
                    message: "Violação de chave estrangeira. Um ou mais valores informados não existem no sistema."
                    status: 400
                DadosInvalidos:
                  summary: Dados inválidos
                  value:
                    message: "Um ou mais valores fornecidos não são válidos"
                    status: 400
                idInvalido:
                  summary: "ID com formato inválido"
                  value:
                    message: "Um ou mais valores fornecidos estão incorretos"
                    status: 400
        "404":
          description: "ID inexistente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: ID fornecido não encontrado
                status: 404
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
    delete:
      tags:
        - Pessoas
      summary: Deleta uma matricula de um usuário
      description: Remove uma matricula pelo seu ID de um usuário pelo seu ID do sistema
      parameters:
        - name: estudante_id
          required: true
          in: path
          description: ID numérico do usuário
          schema:
            type: integer
        - name: id
          in: path
          required: true
          description: ID numérico da matricula
          schema:
            type: integer
      responses:
        "200":
          description: "Registro removido com sucesso!"
          content:
            text/plain:
              schema:
                type: string
                example: "Registro removido com sucesso!"
        "400":
          description: "ID com formato inválido"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: "Um ou mais valores fornecidos estão incorretos"
                status: 400
        "404":
          description: "ID inexistente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: ID fornecido não encontrado
                status: 404
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
  /categorias:
    get:
      tags:
        - Categorias
      summary: Busca as categorias
      description: Retorna as categorias cadastradas no sistema
      parameters:
        - name: titulo
          required: false
          in: query
          description: Titulo da categoria
          schema:
            type: string
        - name: pagina
          required: false
          in: query
          description: Selecionar página/Filtrar por página
          schema:
            type: integer
        - name: limite
          required: false
          in: query
          description: Definir um limite de dados retornados por página
          schema:
            type: integer
        - name: ordem
          required: false
          in: query
          description: Definir ordem de retorno dos dados
          schema:
            type: string
            example: "id:asc"

      responses:
        "200":
          description: Lista de categorias retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CategoriaResponse"
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
    post:
      tags:
        - Categorias
      summary: Cadastra uma nova categoria
      description: Cria uma nova categoria a partir das informações enviadas na requisição
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CategoriaRequest"
      responses:
        "201":
          description: Categoria cadastrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoriaResponse"
        "400":
          description: Erro de validação
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: "Um ou mais valores fornecidos não são válidos"
                status: 400
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
  /categorias/{id}:
    get:
      tags:
        - Categorias
      summary: Busca uma categoria pelo ID
      description: Busca uma categoria pelo ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID numérico da categoria
          schema:
            type: integer
        
      responses:
        "200":
          description: Categoria encontrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoriaResponse"
        "400":
          description: "ID com formato inválido"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                  message: "Um ou mais valores fornecidos estão incorretos"
                  status: 400
        "404":
          description: "ID inexistente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: ID fornecido não encontrado
                status: 404
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
    put:
      tags:
        - Categorias
      summary: Atualiza uma categoria pelo ID
      description: Atualiza uma categoria pelo ID a partir das informações enviadas na requisição
      parameters:
        - name: id
          required: true
          in: path
          description: ID numérico da categoria
          schema:
            type: integer

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CategoriaRequest"
      responses:
        "200":
          description: "Registro atualizado com sucesso!"
          content:
            text/plain:
              schema:
                type: string
                example: "Registro atualizado com sucesso!"
        "400":
          description: Erro de validação ou ID com formato inválido
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              examples:
                DadosInvalidos:
                  summary: Dados inválidos
                  value:
                    message: "Um ou mais valores fornecidos não são válidos"
                    status: 400
                idInvalido:
                  summary: "ID com formato inválido"
                  value:
                    message: "Um ou mais valores fornecidos estão incorretos"
                    status: 400
        "404":
          description: "ID inexistente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: ID fornecido não encontrado
                status: 404
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
    delete:
      tags:
        - Categorias
      summary: Deleta um categoria pelo ID
      description: Remove um categoria do sistema pelo ID
      parameters:
        - name: id
          required: true
          in: path
          description: ID numérico da categoria
          schema:
            type: integer
      responses:
        "200":
          description: "Registro removido com sucesso!"
          content:
            text/plain:
              schema:
                type: string
                example: "Registro removido com sucesso!"
        "400":
          description: "ID com formato inválido"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: "Um ou mais valores fornecidos estão incorretos"
                status: 400
        "404":
          description: "ID inexistente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: ID fornecido não encontrado
                status: 404
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
  /cursos:
    get:
      tags:
        - Cursos
      summary: Busca todos os cursos
      description: Retorna todos os cursos cadastrados no sistema
      parameters:
        - name: titulo
          required: false
          in: query
          description: Titulo do curso
          schema:
            type: string
        - name: descricao
          required: false
          in: query
          description: Descrição do curso
          schema:
            type: string
        - name: categoria_id
          required: false
          in: query
          description: ID da categoria do curso
          schema:
            type: integer
        - name: docente_id
          required: false
          in: query
          description: ID do docente do curso
          schema:
            type: integer
        - name: data_inicial
          required: false
          in: query
          description: Filtrar por um data de inicio
          schema:
            type: string
            format: date
        - name: data_final
          required: false
          in: query
          description: Filtrar por um data final
          schema:
            type: string
            format: date
        - name: pagina
          required: false
          in: query
          description: Selecionar página/Filtrar por página
          schema:
            type: integer
        - name: limite
          required: false
          in: query
          description: Definir um limite de dados retornados por página
          schema:
            type: integer
        - name: ordem
          required: false
          in: query
          description: Definir ordem de retorno dos dados
          schema:
            type: string
            example: "id:asc"

      responses:
        "200":
          description: Lista de cursos retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CursoResponse"
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
    post:
      tags:
        - Cursos
      summary: Cadastra um novo curso
      description: Cria uma novo curso a partir das informações enviadas na requisição
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CursoRequest"
      responses:
        "201":
          description: Curso cadastrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CursoResponse"
        "400":
          description: Erro de validação ou violação de chave estrangeira ou ID com formato inválido
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              examples:
                ViolacaoFK:
                  summary: Violação de chave estrangeira
                  value:
                    message: "Violação de chave estrangeira. Um ou mais valores informados não existem no sistema."
                    status: 400
                DadosInvalidos:
                  summary: Dados inválidos
                  value:
                    message: "Um ou mais valores fornecidos não são válidos"
                    status: 400
                idInvalido:
                  summary: "ID com formato inválido"
                  value:
                    message: "Um ou mais valores fornecidos estão incorretos"
                    status: 400
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
  /cursos/{id}:
    get:
      tags:
        - Cursos
      summary: Busca um curso pelo ID
      description: Retorna um curso pelo ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID numérico do curso
          schema:
            type: integer
        
      responses:
        "200":
          description: Curso encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CursoResponse"
        "400":
          description: "ID com formato inválido"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                  message: "Um ou mais valores fornecidos estão incorretos"
                  status: 400
        "404":
          description: "ID inexistente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: ID fornecido não encontrado
                status: 404
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
    put:
      tags:
        - Cursos
      summary: Atualiza um curso pelo ID
      description: Atualiza um curso pelo ID a partir das informações enviadas na requisição
      parameters:
        - name: id
          required: true
          in: path
          description: ID numérico do curso
          schema:
            type: integer

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CursoRequest"
      responses:
        "200":
          description: "Registro atualizado com sucesso!"
          content:
            text/plain:
              schema:
                type: string
                example: "Registro atualizado com sucesso!"
        "400":
          description: Erro de validação ou ID com formato inválido
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              examples:
                DadosInvalidos:
                  summary: Dados inválidos
                  value:
                    message: "Um ou mais valores fornecidos não são válidos"
                    status: 400
                idInvalido:
                  summary: "ID com formato inválido"
                  value:
                    message: "Um ou mais valores fornecidos estão incorretos"
                    status: 400
        "404":
          description: "ID inexistente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: ID fornecido não encontrado
                status: 404
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
    delete:
      tags:
        - Cursos
      summary: Deleta um curso pelo ID
      description: Remove um curso do sistema pelo ID
      parameters:
        - name: id
          required: true
          in: path
          description: ID numérico do curso
          schema:
            type: integer
      responses:
        "200":
          description: "Registro removido com sucesso!"
          content:
            text/plain:
              schema:
                type: string
                example: "Registro removido com sucesso!"
        "400":
          description: "ID com formato inválido"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: "Um ou mais valores fornecidos estão incorretos"
                status: 400
        "404":
          description: "ID inexistente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
              example:
                message: ID fornecido não encontrado
                status: 404
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
  /matriculas:
    get:
      tags:
        - Matriculas
      summary: Busca todas as matriculas
      description: Retorna todas as matriculas cadastradas no sistema
      parameters:
        - name: estudante_id
          required: false
          in: query
          description: ID do estudante da matricula
          schema:
            type: integer
        - name: curso_id
          required: false
          in: query
          description: ID do curso da matricula
          schema:
            type: integer
        - name: status
          required: false
          in: query
          description: Status da matricula (matriculado ou cancelado)
          schema:
            type: string
        - name: pagina
          required: false
          in: query
          description: Selecionar página/Filtrar por página
          schema:
            type: integer
        - name: limite
          required: false
          in: query
          description: Definir um limite de dados retornados por página
          schema:
            type: integer
        - name: ordem
          required: false
          in: query
          description: Definir ordem de retorno dos dados
          schema:
            type: string
            example: "id:asc"

      responses:
        "200":
          description: Lista de matriculas retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MatriculaResponse"
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"
  /matriculas/cursos-lotados:
    get:
      tags:
        - Matriculas
      summary: Busca os cursos lotados
      description: Busca os cursos lotados e quantidade de matriculas existente no curso
      parameters:
        - name: pagina
          required: false
          in: query
          description: Selecionar página/Filtrar por página
          schema:
            type: integer
        - name: limite
          required: false
          in: query
          description: Definir um limite de dados retornados por página
          schema:
            type: integer
        - name: ordem
          required: false
          in: query
          description: Definir ordem de retorno dos dados
          schema:
            type: string
            example: "id:asc"
      responses:
        "200":
          description: Lista de cursos lotados retornadas com sucesso!
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: array
                    items:
                      type: object
                      properties:
                        curso_id:
                          type: integer
                          example: 1
                        count:
                          type: integer
                          example: 2
                  rows:
                    type: array
                    items:
                      type: object
                      properties:
                        curso_id:
                          type: integer
                          example: 1
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErroResponse"

components:
  schemas:
    ErroResponse:
      type: object
      properties:
        message:
          type: string
          example: "Erro interno do servidor"
        status:
          type: integer
          example: 500

    SequelizeBase:
      type: object
      properties:
        id:
          type: integer
          example: 1
        createdAt:
          type: string
          format: date-time
          example: "2026-05-17T01:36:26.247Z"
        updatedAt:
          type: string
          format: date-time
          example: "2026-06-23T03:23:48.624Z"
        deletedAt:
          type: string
          format: date-time
          nullable: true
          example: null

    PessoaRequest:
      type: object
      required:
        - nome
        - email
        - cpf
        - ativo
        - role
      properties:
        nome:
          type: string
          example: "Solange Estudante"
        email:
          type: string
          example: "solange@email.com"
        cpf:
          type: string
          example: "63058133022"
        ativo:
          type: boolean
          example: true
        role:
          type: string
          example: "estudante"

    PessoaResponse:
      allOf:
        - $ref: "#/components/schemas/PessoaRequest"
        - $ref: "#/components/schemas/SequelizeBase"
    
    CategoriaRequest:
      type: object
      required:
        - titulo
      properties:
        titulo:
          type: string
          example: "Node.js"

    CategoriaResponse:
      allOf:
        - $ref: "#/components/schemas/CategoriaRequest"
        - $ref: "#/components/schemas/SequelizeBase"
    
    CursoRequest:
      type: object
      required:
        - titulo
        - data_inicio
        - categoria_id
        - docente_id
      properties:
        titulo:
          type: string
          example: "API com Express"
        data_inicio:
          type: string
          format: date
          example: "2023-01-01"
        categoria_id:
          type: integer
          description: "ID da categoria do curso (FK)"
          example: 1
        docente_id:
          type: integer
          description: "ID do docente do curso (FK)"
          example: 5
    
    CursoResponse:
      allOf:
        - $ref: "#/components/schemas/CursoRequest"
        - $ref: "#/components/schemas/SequelizeBase"

    MatriculaRequest:
      type: object
      required:
        - curso_id
        - status
      properties:
        curso_id:
          type: integer
          description: "ID do curso da matricula (FK)"
          example: 1
        status:
          type: string
          example: "matriculado"

    MatriculaRequestToResponse:
      type: object
      required:
        - estudante_id
        - curso_id
        - status
      properties:
        estudante_id:
          type: integer
          description: "ID do estudante (FK)"
          example: 1
        curso_id:
          type: integer
          description: "ID do curso da matricula (FK)"
          example: 1
        status:
          type: string
          example: "matriculado"

    MatriculaResponse:
      allOf:
        - $ref: "#/components/schemas/MatriculaRequestToResponse"
        - $ref: "#/components/schemas/SequelizeBase"